#+title: Le pistolet sur la tempe

Début juin 1940, c’est la débacle en France, les Allemands ont atteint
la Manche depuis le mois de mai et menacent le Royaume-Uni. Émile prit
part à la résistance héroïque française pendant la bataille de
Dunkerque pour permettre aux troupes britanniques et canadiennes
d’évacuer. Tout son bataillon fut décimé, il partit lui-même dans les
derniers bateaux. Arrivé au Royaume-Uni, après quelques entretiens, il
fut affecté à une étrange branche de l’armée, la Section M.

Alexander Towton participa lui-même à l’entertien que passa Émile à la
section M. Après de nombreux tests et lui avoir expliquer ce dont il
était question, Towton demanda à Émile s’il voulait rejoindre la
section. Émile resta un instant silencieux avant de dire : « Je
pourrais avoir un Springfield M1903 ?
— Qu’est-ce que c’est ?
— Un fusil américain.
— Ho oui, on va vous trouver ça.
— Avec une lunette de visée ?
— Oui, bien sûr.
— Alors je veux bien. »

Une fois partie, Towton dit aux membres de la section présente :
encore une excellente recrue. Typique de la section M.

* Acte 1 : Les falaises blanches de Douvres

** Scène 1 : Un télégramme

C’est dans cette ambiance internationale morose que chacun d’entre vous
reçoit ce télégramme :

#+BEGIN_QUOTE
+++ PRÉPAREZ VOUS À PARTIR IMMÉDIATEMENT STOP PRÉVOIR UNE SEMAINE
D’ABSENCE STOP INSTRUCTIONS ET TITRE DE TRANSPORT ARRIVERONT PAR
MESSAGER STOP URGENT ET SECRET+++
#+END_QUOTE

Vous reconnaissez le style de la Section M. Quelques heures plus tard
un messager en uniforme de l’armée se présente à vous avec des billets
pour la gare de Dover Priory par le train de 10h15 partant de Victoria
Station. Il vous donne aussi une lettre :

#+BEGIN_QUOTE
Cher <votre nom>,

Vous avez ordre de vous rendre immédiatement à Douvre en train, comme
il est indiqué sur vos billets. Vous serez accueilli à la station par
le sergent Briggs de la Royal Artillery. Il vous briefera sur une
situation urgente qui est apparu à cet endroit.  Il est de la plus
haute importance que la situation soit résolu rapidement et avec le
plus grand secret et devra être envoyé à la section M, ABS du
Metropole Hotel.
#+END_QUOTE

