#+title: Le pistolet sur la tempe

* Introduction

Début juin 1940, c’est la débâcle en France, les Allemands ont atteint
la Manche depuis le mois de mai et menacent le Royaume-Uni. Émile prit
part à la résistance héroïque française pendant la bataille de
Dunkerque pour permettre aux troupes britanniques et canadiennes
d’évacuer. Tout son bataillon fut décimé, il partit lui-même dans les
derniers bateaux. Arrivé au Royaume-Uni, après quelques entretiens, il
fut affecté à une étrange branche de l’armée, la Section M.

Alexander Towton participa lui-même à l'entretien que passa Émile à la
section. Après de nombreux tests et lui avoir expliquer ce dont il
était question, Towton demanda à Émile s’il voulait rejoindre la
section. Émile resta un instant silencieux avant de répondre :

« Je pourrais avoir un Springfield M1903 ?

— Qu’est-ce que c’est ?

— Un fusil américain.

— Ho oui, on va vous trouver ça.

— Avec une lunette de visée ?

— Oui, bien sûr.

— Alors je veux bien. »

Une fois partie, l’affable lieutenant Archibald Strang dit aux membres
de la section présente : « un étranger inexpressif et
inquiétant. Encore une excellente recrue. Typique de la section M. »

* Acte 1 : Les falaises blanches

** Scène 1 : Un télégramme

C’est dans cette ambiance internationale morose que chacun d’entre vous
reçoit ce télégramme :

#+BEGIN_QUOTE
+++ PRÉPAREZ VOUS À PARTIR IMMÉDIATEMENT STOP PRÉVOIR UNE SEMAINE
D’ABSENCE STOP INSTRUCTIONS ET TITRE DE TRANSPORT ARRIVERONT PAR
MESSAGER STOP URGENT ET SECRET+++
#+END_QUOTE

Vous reconnaissez le style de la Section M. Quelques heures plus tard
un messager en uniforme de l’armée se présente à vous avec des billets
pour la gare de Dover Priory par le train de 10h15 partant de Victoria
Station. Il vous donne aussi une lettre :

#+BEGIN_QUOTE
Cher <votre nom>,

Vous avez ordre de vous rendre immédiatement à Douvre en train, comme
il est indiqué sur vos billets. Vous serez accueilli à la station par
le sergent Briggs de la Royal Artillery. Il vous brifera sur des
circonstances urgentes qui sont apparues à cet endroit.  Il est de la
plus haute importance que ces dernières soient résolues rapidement et
avec le plus grand secret. Une fois que c’est fait un rapport écrit
devra être envoyé à la section M, ABS du Metropole Hotel.

— Strang
#+END_QUOTE

Victoria Station grouille de monde. Vous arrivez à Douvre un peu avant
une heure de l’après-midi. En descendant du quai vous voyez un
militaire tenir un panneau avec votre nom de marqué dessus et le nom
de trois autres personnes que vous ne connaissez pas.

Renato demande s'il peut conduire, mais le sergent refuse. Jean essaye
de lui tirer quelques informations, mais le sergent préfère attendre
pour répondre aux questions. Les héros montent dans le camion qui part
tout de suite. Ce dernier quitte Douvre et suit la côte, avant de
repartir dans les terres. Au bout de quinze minutes il arrive sur une
longue allée arborée et s'arrête devant une imposante demeure.

** Scène 2 : Bulney Grange

Vous voyez une majestueuse habitation transformée en hôpital
militaire. Plusieurs ambulance sont garées à l'extérieur. Vous voyez
des patients se promener ou se détendre sur des chaises longues. le
sergent Briggs vous amène à une bibliothèque bien garnie où vous
attendent du thé et des sandwichs. Briggs vous invite à vous servir et
vous asseoir.

« Veuillez nous pardonner d'avoir demandé de l'assistance en urgence,
mais nous sommes complètement décontenancés et perdus. Quelles sont
les informations que le bureau de la guerre vous à donné avant de
venir ? »

Après la réponse négatives des héros, le sergent Briggs enchaîne :

« Vous avez peut-être entendu parler dans la presse de la découverte
d’un ancien fort breton près de Douvre. Nous sommes en train de monter
des gros canons sur les falaises blanches. Programme de défense contre
l’invasion. En creusant un tunnel pour acheminer les munitions nous
sommes tombés sur un étrange pilier en pierre pris dans le
calcaire. Cambridge a envoyé un archéologue. Le Docteur Edward Bland,
et il a trouvé un genre de construction dans le calcaire. Du jamais vu
comme il dit. Maintenant, il est ici, avec mon capitaine et quatre de
mes hommes qui creusaient pour lui.

Ils ont tous la même chose : ils se plaignent de cauchemars, ils ont
des hallucinations... Nous n’avons pas encore été sous le feu de
l’ennemi, ce n’est donc pas une obusite. C’est quelque chose de
nerveux. Ceux qui ont le plus creusé sont dans le plus mauvais
état. J’y ai passé une tête une fois, et j’en suis ressorti avec un
genre de mal de mer. C’est passé après une heure, mais je me suis
senti mal à l’aise. Je ne veux pas y retourner.

J’ai rapporté que mon capitaine a été hospitalisé et le Bureau de l’a
Guerre m’a dit qu’ils allaient m’envoyer des experts. »

Briggs semble soulagé d’avoir fini son récit. Il vous regarde
intensément, il attend de vous que vous lui donniez des réponses à
tout cela.

Renato cherche à savoir si on peut creuser ailleurs. C’est le Bureau
de la guerre qui décidera. Renato veut savoir comment se porte
l’archéologue, Briggs lui répond pas très bien, mais vous aurez
l’occasion de le voir. Asha demande s’il y a des sépultures. Aucune
n’a été trouvée. Jean veut savoir quel type de cauchemard font les
gens, le sergent ne le sait pas.

** Scène 3 : l’hôpital

Briggs vous présente le docteur Reginald Pinner. Ce dernier vous
dresse l’état des lieux.

« Tous les patients montrent des signes naissant de paranoia, de
confusion et souffrent d’hallucination légère. Ils souffrent de
cauchemar et se réveillent souvent en criant. Ils sont tous
mortellement effrayés de retourner sur le lieu de l’excavation et
disent rêver des terribles danger qu’il y a là bas._» Il nettoie ses
lunettes et s’éclaircit la gorge. « Je ne sais pas si c’est
significatif, mais nous eûmes un petit incident au dîner hier
soir. J’ai pu mettre la main sur un joli lot de maquereau frais, pêché
localement, et je me suis dit que cela changerait agréablement de
l’ordinaire. Ils ont tous montré une étrange aversion pour le
poisson. Deux d’entre eux ont dû être maîtrisé physiquement. Après
coup, ils étaient dans l’impossibilité de justifier leur action si ce
n’est qu’ils avaient une grande aversion pour le poisson. Je n’ai
aucune idée de ce que je peux faire de ça. »

Le docteur Pinner vous propose de rencontrer les patients. Ils sont
six en tout, l’archéologue de Cambridge, le Docteur Edward Bland, le
capitaine Featherstone, et les cannoniers Brown, Day, Larkin et
Roberts.

Le plus affecté semble être le docteur Bland. Ses mains tremblent, il
a le regard dans le vide et marmonne des choses incompréhensibles.
